---
galaxy_info:
  author: Sebastien Perreault
  description: Gateway Role for ScaleIO
  company: EMC Corporation
  license: MIT
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - 6
    - 7

  - name: Ubuntu
    versions:
    - trusty

  categories:
   - system

  dependencies:
   - scaleio-common
